chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
  console.log("Send");
  chrome.tabs.sendMessage(tabs[0].id, "message", (response) => {
    console.log("body response =" + response.body);
    function detectDarkPatterns(paragraph) {
      // List of deceptive words and phrases
      const deceptiveWords = [
        "hurry",
        "has virus",
        "limited time offer",
        "act now",
        "almost sold out",
        "attacked",
        "install now to",
        "you have been",
        "you are",
        "free trial, credit card required",
        "cancel anytime, but before the next billing cycle",
        "opt-out subscription",
        "get rich quick",
        "make money fast",
        "exclusive deal",
        "prize winner",
        "guaranteed",
        "urgent",
        "risk-free",
        "winning",
        "pre-approved",
        "one-time",
        "hidden",
        "double your",
        "money back",
        "special promotion",
        "extra cash",
        "limited-time",
        "as seen on",
        "cash bonus",
        "earn $",
        "no catch",
        "hidden charges",
        "no cost",
        "free investment",
        "discount",
        "bonus",
        "bargain",
        "lowest price",
        "unbeatable",
        "instant",
        "one hundred percent free",
        "winner",
        "winning",
        "congratulations",
        "increase sales",
        "multi-level marketing",
        "mass email",
        "be your own boss",
        "reverses aging",
        "search engine listings",
        "social security number",
        "no hidden",
        "promise",
        "no strings attached",
        "this isn't a scam",
        "cancel anytime",
        "hidden assets",
        "no credit check",
        "100% satisfied",
        "fast cash",
        "earn extra cash",
        "best price",
        "big bucks",
        "cents on the dollar",
        "consolidate debt",
        "copy accurately",
        "dig up dirt on friends",
        "direct email",
        "double your income",
        "double your investment",
        "earn extra cash",
        "eliminate bad credit",
        "extra cash",
        "fantastic",
        "financial freedom",
        "for just $",
        "free access",
        "free gift",
        "free membership",
        "free money",
        "free preview",
        "full refund",
        "get out of debt",
        "get paid",
        "guarantee",
        "hidden",
        "hidden assets",
        "hidden charges",
        "increase sales",
        "investment",
        "lose weight",
        "mass email",
        "miracle",
        "multi-level marketing",
        "no cost",
        "no credit check",
        "no fees",
        "not spam",
        "one hundred percent free",
        "opportunity",
        "please read",
        "potential earnings",
        "pure profit",
        "removal instructions",
        "reverses",
        "safeguard notice",
        "search engine listings",
        "social security number",
        "special promotion",
        "this isn't a scam",
        "unsecured credit",
        "urgent",
        "we hate spam",
        "weekend getaway",
        "weight",
        "what are you waiting for?",
        "while you sleep",
        "will not believe your eyes",
        "winner",
        "winning",
        "work from home",
        "you are a winner!",
        "secret method",
        "cash flow",
        "amazing results",
        "double your cash",
        "bonus cash",
        "for free!",
        "hidden fees",
        "instant cash",
        "money-making",
        "lowest price ever",
        "risk-free trial",
        "limited supply",
        "exclusive access",
        "no strings attached",
        "get started now",
        "not a scam",
        "once in a lifetime",
        "winner guaranteed",
        "miracle solution",
        "no hidden fees",
        "stop snoring",
        "your income",
        "money-back guarantee",
        "100% satisfaction",
        "free investment",
        "act immediately",
        "hidden from",
        "meet singles",
        "stop aging",
        "extra income",
        "cash bonus",
        "earn per week",
        "hidden charges",
        "limited time",
        "money you need",
        "online marketing",
        "satisfaction guaranteed",
        "be your own boss",
        "mass email",
        "in accordance with laws",
        "print form signature",
        "direct email marketing",
        "no credit check",
        "dear friend",
        "no catch",
        "no cost",
        "no fees",
        "no gimmick",
        "no hidden",
        "no hidden fees",
        "no interest",
        "no investment",
        "no medical exams",
        "no middleman",
        "no obligation",
        "no purchase necessary",
        "no questions asked",
        "no selling",
        "no strings attached",
        "not spam",
        "promise",
        "satisfaction",
        "social security number",
        "this isn't a scam",
        "this isn't spam",
        "this won't believe",
        "unsecured credit",
        "urgent",
        "weekend getaway",
        "what are you waiting for?",
        "while you sleep",
        "will not believe your eyes",
        "winner",
        "winning",
        "work at home",
        'click "allow"',
        // Add more deceptive words as needed
      ];

      // Convert the paragraph to lowercase for case-insensitive matching
      const lowercaseParagraph = paragraph.toLowerCase();

      // Check if any deceptive words are present in the paragraph
      const foundDeceptiveWords = deceptiveWords.filter((word) =>
        lowercaseParagraph.includes(word.toLowerCase())
      );

      return foundDeceptiveWords;
    }

    // Example usage
    const paragraphToCheck = response.body;
    const foundWords = detectDarkPatterns(paragraphToCheck);
    if (foundWords.length > 0) {
      console.log("Deceptive words found.", foundWords);
      document.getElementById("title").innerText = "Deceptive words found!";
      document.getElementById("title").style.color="red";
    } else {
      console.log("No deceptive words found.");
      document.getElementById("title").innerText = "No deceptive words found.";
      document.getElementById("title").style.color="green";
    }
  });
});
